IOFacade & GraphicsFacade
PixNyb/Avans-SPCPRJ13-ENGINE pull request #30
Opened 2023-11-13 14:15 UTC by RobinPijnappelsAvans

2023-11-13 14:42 UTC, PixNyb requested changes

2023-11-13 14:42 UTC, PixNyb commented on include/facades/graphics_facade.hpp
> +
Waar is deze doc heen

2023-11-13 14:42 UTC, PixNyb commented on include/facades/io_facade.hpp
> +    virtual void SetupWindow(const char* title, int width, int height) = 0;
Documentatie

2023-11-13 14:42 UTC, PixNyb commented on include/facades/io_facade.hpp
> +    virtual void ClearScreen() = 0;
Documentatie

2023-11-13 14:42 UTC, PixNyb commented on include/facades/io_facade.hpp
> +    virtual void CreateRenderer() = 0;
Documentatie

2023-11-13 14:42 UTC, PixNyb commented on include/facades/io_facade.hpp
> +    virtual void PresentScreen() = 0;
Documentatie

2023-11-13 14:42 UTC, PixNyb commented on sandbox/main.cpp
Revert de sandbox even

2023-11-13 14:42 UTC, PixNyb commented on src/facades/sdl2/sdl_init.cpp
> +//
Gebruik standaard file header

2023-11-13 14:42 UTC, PixNyb commented on src/project/core/engine.cpp
> +    graphicsFacade->CreateWindow("Init window", 800, 600);
Uitbesteden aan de game

2023-11-13 16:20 UTC, PixNyb commented on include/facades/graphics_facade.hpp
> +    void CreateWindow(const char* title, int width, int height) override;
Waarom bestaat dit als SetupWindow bestaat?

2023-11-13 16:21 UTC, PixNyb commented on src/facades/graphics_facade.cpp
> +    SdlWindow->Create(title, width, height);
Waarom kan ik dit niet los van CreateWindow callen? Ivm SetupWindow

2023-11-13 21:18 UTC, PixNyb commented on sandbox/main.cpp
Revert deze nou

2023-11-14 08:57 UTC, RobinPijnappelsAvans commented on sandbox/main.cpp
Hoezo revert? er staat letterlijk niks in

2023-11-14 09:03 UTC, RobinPijnappelsAvans commented on include/project/core/engine.hpp
>      static Engine *GetInstance()
@PixNyb, slecht nagekeken bij @ChocoMelvin want dit stond er al in. I only made it shorter, but i shall fix it eh

2023-11-14 09:10 UTC, PixNyb requested changes

2023-11-14 09:10 UTC, PixNyb commented on USAGE.md
> +TODO: Verder uitwerken als straks alles op zijn plek staat (woensdag)
Werk uit dan

2023-11-14 09:10 UTC, PixNyb commented on src/facades/graphics_facade.cpp
> +#include "graphics_facade.hpp"
File header anders word ie niet meegenomen in doxygen

2023-11-14 09:10 UTC, PixNyb commented on src/project/core/game_loop.cpp
>  //
Kan t niet zien in de view maar vgm is dit ook geen standaard header

2023-11-14 09:11 UTC, PixNyb commented on sandbox/main.cpp
<img width="988" alt="image" src="https://github.com/PixNyb/Avans-SPCPRJ13-ENGINE/assets/40770831/51ab6e67-f7b7-4ad4-917f-0470f34664a0">

2023-11-14 09:27 UTC, RobinPijnappelsAvans commented on USAGE.md
> +TODO: Verder uitwerken als straks alles op zijn plek staat (woensdag)
Neej, moeten nog bespreken hoe we t willen gaan doen samen met Melvin

2023-11-14 09:30 UTC, RobinPijnappelsAvans commented on sandbox/main.cpp
Ik snap jou niet je wilt toch gewoon dat die leeg is en iedereen zn eigen ding kan doen?

2023-11-14 09:42 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +Engine *Engine::GetInstance() {
Wist niet dat je statics ook apart mocht definiëren, nice.

2023-11-14 09:42 UTC, ChocoMelvin commented on src/project/core/game_loop.cpp
Hoeft het er niet uit te halen, maar denk dat deze niet meer nodig is? Kunnen we later wel tijdens een clean-up doen

2023-11-14 09:43 UTC, ChocoMelvin approved these changes

2023-11-14 09:53 UTC, PixNyb approved these changes
<img width="140" alt="image" src="https://github.com/PixNyb/Avans-SPCPRJ13-ENGINE/assets/40770831/509456a8-bdfe-4728-9921-0a7927aa6bee">

2023-11-14 09:53 UTC, merged