Feature/level -> Development
PixNyb/Avans-SPCPRJ13-ENGINE pull request #32
Opened 2023-11-16 16:44 UTC by Maxuuuu

Content van de PR:
- JSONReader
- AbstractSceneFactory
- LevelFactory
- PrefabManager
- Copy assignment operator en copy constructor voor het GameObject.

Ook is er een package toegevoegd voor het uitlezen van de JSON. 
https://github.com/nlohmann/json

2023-11-16 20:43 UTC, PixNyb requested changes
🍝🍝

2023-11-16 20:43 UTC, PixNyb commented on include/api/game_object.hpp
> +    GameObject(const GameObject& other);
Document

2023-11-16 20:43 UTC, PixNyb commented on include/api/game_object.hpp
> +    GameObject &operator=(const GameObject &other);
Document

2023-11-16 20:43 UTC, PixNyb commented on include/api/game_object.hpp
> +    GameObject(GameObject &&other) noexcept = delete;
Document

2023-11-16 20:43 UTC, PixNyb commented on include/api/game_object.hpp
> +    GameObject& operator=(GameObject &&other) noexcept = delete;
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/managers/prefab_manager.hpp
> +    PrefabManager();
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/managers/prefab_manager.hpp
> +    std::map<std::string, GameObject> prefabs;
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/managers/prefab_manager.hpp
> +#include "../../api/game_object.hpp"
Wat is dit

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/abstract_scene_factory.hpp
> +#include "../../../api/scene.hpp"
🍝🍝🍝

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/abstract_scene_factory.hpp
> +    AbstractSceneFactory() = default;
Document(?)

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/level_factory.hpp
> +#include "../../managers/prefab_manager.hpp"
Nog meer spaghetti

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/level_factory.hpp
> +    std::shared_ptr<PrefabManager> prefabManager;
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/level_factory.hpp
> +    std::vector<std::shared_ptr<GameObject>> addObjects(Scene &scene, const nlohmann::json& objectsJson);
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/json_reader.hpp
> +    JSONReader() = default;
Document

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/json_reader.hpp
> +#include "nlohmann/json.hpp"
Zie coding guidelines, externe libraries met <> ipv "". "" is voor lokale files en <> voor system headers (/externe libs)

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/level_factory.hpp
> +#include "memory"
<>

2023-11-16 20:43 UTC, PixNyb commented on include/project/utility/factories/abstract_scene_factory.hpp
> +#include "nlohmann/json.hpp"
<>

2023-11-16 20:43 UTC, PixNyb commented on src/project/managers/prefab_manager.cpp
> +#include "../../../include/project/managers/prefab_manager.hpp"
Nog meer spaghet🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝🍝

2023-11-16 20:43 UTC, PixNyb commented on src/project/managers/prefab_manager.cpp
> +#include "format"
System header

2023-11-16 20:43 UTC, PixNyb commented on src/project/utility/json_reader.cpp
> +#include "nlohmann/json.hpp"
System header

2023-11-17 08:54 UTC, RobinPijnappelsAvans commented
@Maxuuuu, ik close ff de PR tot dat je weer ready bent maat

2023-11-17 14:13 UTC, Maxuuuu commented on include/project/utility/json_reader.hpp
> +#include "nlohmann/json.hpp"
Ik heb dit voor alle include's aangepast, verder sluit ik al deze comments en ga ik verder met het toevoegen van documentatie.

2023-11-17 15:18 UTC, PixNyb requested changes

2023-11-17 15:18 UTC, PixNyb commented on CMakeLists.txt
> +find_package(nlohmann_json CONFIG REQUIRED)
Wil je deze ook even aan tests/CMakeLists.txt toevoegen

2023-11-19 10:00 UTC, RobinPijnappelsAvans reviewed
@Maxuuuu, couple suggestions but the rest looks good mate

2023-11-19 11:27 UTC, Maxuuuu commented on include/api/scene.hpp
> +        // TODO: Write implementation.
Nja ik moet een specifieke instance van Scene kunnen maken, en het is dus eigenlijk meer de vraag waarom dit überhaupt virtual is op het moment. Zonder een huidige implementatie kan ik er geen instance van maken.

2023-11-19 11:28 UTC, Maxuuuu commented on sandbox/CMakeLists.txt
Heb hem ook enkel aangepast, en het lijkt mij juist dat alle benodigde dependencies er gewoon in moeten staan. Anders moet iemand die de sandbox wil gaan gebruiken eerst dit allemaal fixen voordat je het kan builden.

2023-11-19 11:31 UTC, Maxuuuu commented on src/project/utility/factories/abstract_scene_factory.cpp
Hier hoeft eigenlijk niks zo zeer te gebeuren. We hebben hier nog geen concreet ontwerp voor. Verder begreep ik dat de conventie was dat er altijd voor een hpp file een bijbehorende cpp file moest zijn, als dat niet zo is kan deze file er op zich uit.

2023-11-19 11:45 UTC, RobinPijnappelsAvans commented on sandbox/CMakeLists.txt
lol your right

2023-11-19 15:14 UTC, DaanGroot536 commented on src/project/utility/factories/level_factory.cpp
> +std::vector<std::shared_ptr<GameObject>> LevelFactory::addObjects(Scene &scene, const nlohmann::json& objectsJson) {
AddObjects ipv addObjects?

2023-11-19 15:15 UTC, DaanGroot536 commented on src/project/utility/factories/level_factory.cpp
> +Transform LevelFactory::convertTransform(const nlohmann::json &transformJson) const
ConvertTransform ipv convertTransform?

2023-11-19 15:20 UTC, DaanGroot536 commented on USAGE.md
> +      "objects": []
wat houdt objects exact in als het in een object zelf staat. Children?

2023-11-19 15:21 UTC, DaanGroot536 reviewed
Heb wat kleine casing dingetjes gespot. snap zelf niet helemaal nog wat je met objects in een object zelf bedoelt

2023-11-19 19:41 UTC, ChocoMelvin requested changes
Op zich prima, hier en daar wat kleine verbeteringen.

2023-11-19 19:41 UTC, ChocoMelvin commented on src/api/scene.cpp
> -void Scene::RenderScene() {}
Waarom verwijder je in een level PR functies uit een scène?

2023-11-19 19:41 UTC, ChocoMelvin commented on src/project/managers/prefab_manager.cpp
> +void PrefabManager::RegisterPrefab(const std::string& tag, const GameObject& prefab)
Kijk even naar je naamgeving. Een tag kan in de unity wereld meerdere dingen betekenen, het is iig zeker geen uniek identificeerbaar iets in unity.

2023-11-19 19:41 UTC, ChocoMelvin commented on src/project/utility/factories/level_factory.cpp
Het is gewoon de fout van de gebruiker als er iets fout wordt ingevoerd, maar mochten we dat af moeten vangen om te tonen, dan kan dat neem ik aan?

2023-11-19 19:41 UTC, ChocoMelvin commented on include/project/utility/factories/level_factory.hpp
> +    [[nodiscard]] Scene CreateScene(nlohmann::json sceneJson) override;
Hmm, waarom return je hier een hele Scene by copy?

2023-11-19 19:48 UTC, PixNyb commented on src/project/utility/factories/abstract_scene_factory.cpp
Complete virtual/abstract classes/interfaces hoeven geen cpp file, zorg wel ff dat je de file/class iscene_factory.hpp noemt enz. Staat niet vast maar melvin heeft al klasses met i geprefixed

2023-11-19 19:50 UTC, PixNyb commented on USAGE.md
> +      "objects": []
Zou m idd eerder `children`, `prefabs` of iets in die richting noemen

2023-11-20 08:47 UTC, ChocoMelvin commented on include/api/scene.hpp
> +        // TODO: Write implementation.
Jawel, door een scene te maken (in de game/sandbox, die evan overerft).
Dit is niet handig.

2023-11-20 11:03 UTC, Maxuuuu commented on include/api/scene.hpp
> +        // TODO: Write implementation.
Er is nu een LevelScene geïmplementeerd die dit probleem oplost.

2023-11-20 11:06 UTC, Maxuuuu commented on src/project/utility/factories/abstract_scene_factory.cpp
Dit moet helaas wel, zonder deze file build het project überhaupt niet.

2023-11-20 11:06 UTC, Maxuuuu commented on src/project/utility/factories/level_factory.cpp
> +Transform LevelFactory::convertTransform(const nlohmann::json &transformJson) const
Je hebt gelijk, heb ik bijgewerkt.

2023-11-20 11:07 UTC, Maxuuuu commented on USAGE.md
> +      "objects": []
Om verwarring te voorkomen heb ik het naar children veranderd. Het stond wel al in de bovenstaande documentatie toeglicht.

2023-11-20 11:09 UTC, Maxuuuu commented on src/project/utility/factories/level_factory.cpp
Er dient inderdaad een try catch om heen te staan, dit is grondig getest en is goed uit te lezen. Dit geldt beide voor de factory en de jsonreader.

2023-11-20 11:09 UTC, Maxuuuu commented on include/project/utility/factories/level_factory.hpp
> +    [[nodiscard]] Scene CreateScene(nlohmann::json sceneJson) override;
Goede opmerking, returned nu een shared pointer.

2023-11-20 11:09 UTC, Maxuuuu commented on src/project/managers/prefab_manager.cpp
> +void PrefabManager::RegisterPrefab(const std::string& tag, const GameObject& prefab)
Heb de tag naar id veranderd om verdere verwarring te voorkomen.

2023-11-20 12:35 UTC, DaanGroot536 submitted a review, later dismissed
guten

2023-11-20 12:50 UTC, PixNyb submitted a review, later dismissed

2023-11-20 20:54 UTC, ChocoMelvin requested changes
Een klein dingetje nog :(

2023-11-20 20:54 UTC, ChocoMelvin commented on include/project/utility/factories/iscene_factory.hpp
>    public:
Pure abstract klasse en interfaces moeten volgens mij een virtuele destructor hebben.

2023-11-20 21:12 UTC, ChocoMelvin approved these changes

2023-11-20 21:20 UTC, merged