Feature/rendersystem
PixNyb/Avans-SPCPRJ13-ENGINE pull request #34
Opened 2023-11-17 11:16 UTC by RobinPijnappelsAvans

2023-11-17 11:59 UTC, RobinPijnappelsAvans commented
@PixNyb DEZE NIET MERGEN OULEH!!!!!!!!!
<details><summary>Details</summary>
<p>

whoopwhoop

</p>
</details>

2023-11-18 15:03 UTC, PixNyb requested changes
Zie verder graag wat meer comments in de implementatiefiles, maar all in all looks good.

2023-11-18 15:25 UTC, ChocoMelvin commented on include/project/graphics/shapes/circle.hpp
> +    int GetArea() override {
nee

2023-11-18 15:25 UTC, ChocoMelvin commented on include/project/graphics/shapes/circle.hpp
> +    [[nodiscard]] Vector2D GetPosition() const {
nee

2023-11-18 15:49 UTC, ChocoMelvin commented on include/project/graphics/shapes/line.hpp
> +#include "color.hpp"
Denk dat dit in point al geinclude was, handiger om het er extra bij te zetten idd.

2023-11-18 15:49 UTC, ChocoMelvin commented on include/project/graphics/shapes/polygon.hpp
> +    int GetArea() override {
nee.

2023-11-18 15:50 UTC, ChocoMelvin commented on include/project/graphics/shapes/polygon.hpp
> +        return std::abs(area) / 2;
nee, std lib zit er standaard in??

2023-11-18 15:52 UTC, ChocoMelvin commented on include/project/graphics/shapes/triangle.hpp
>      Vector2D vertex1, vertex2, vertex3;
no.

2023-11-18 15:52 UTC, ChocoMelvin commented on include/project/graphics/shapes/triangle.hpp
> +    int GetArea() override {
no

2023-11-18 15:52 UTC, ChocoMelvin commented on include/project/graphics/shapes/triangle.hpp
> +    bool IsWithinArea(const Vector2D& start, const Vector2D& end) override {
no.

2023-11-18 15:55 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +        while (SDL_PollEvent(&event)) {
Omdat input manager er nog niet is.

2023-11-18 16:30 UTC, PixNyb commented on include/api/scene.hpp
> +     * TODO: Check if this is really the case?
@todo niet TODO:
```suggestion
     * @todo Check if this is really the case?
```

2023-11-18 16:33 UTC, PixNyb commented on include/project/graphics/shapes/polygon.hpp
> +    int GetArea() override {
Nogsteeds implementatie in header file tho

2023-11-18 16:34 UTC, PixNyb commented on src/project/core/engine.cpp
> +        while (SDL_PollEvent(&event)) {
Fair enough

2023-11-19 19:50 UTC, ChocoMelvin commented on include/api/scene.hpp
> +     * TODO: Check if this is really the case?
Alleen als je dit tegen doxygen wil vertellen.

2023-11-20 09:01 UTC, PixNyb approved these changes

2023-11-20 10:02 UTC, merged