Feat/input
PixNyb/Avans-SPCPRJ13-ENGINE pull request #38
Opened 2023-11-18 12:48 UTC by Martijn-V1

2023-11-18 13:50 UTC, PixNyb commented on include/api/ikey_listener.hpp
@param docs

2023-11-18 13:50 UTC, PixNyb commented on include/api/imouse_listener.hpp
>       */
@param docs

2023-11-18 13:50 UTC, PixNyb commented on include/api/imouse_listener.hpp
>       */
@param docs

2023-11-18 14:05 UTC, PixNyb requested changes
Sandbox lijkt verder te runnen, vul aub aan met unit tests in de /tests folder volgens [development guidelines](/DEVELOPMENT_GUIDELINES.md#86) en update je branch.

2023-11-18 14:05 UTC, PixNyb commented on src/project/listeners/key_listener.cpp
> +            }
Maak hier aub een switch van:

```suggestion
            switch (enumOfType) {
                case ActionType::JUMP:
                    break;
                case ActionType::GODOWN:
                    break;
                case ActionType::GOUP:
                    break;
                case ActionType::GOLEFT:
                    break;
                case ActionType::GORIGHT:
                    break;
                case ActionType::PAUSE:
                    break;
                default:
                    break;
            }
```

2023-11-18 14:05 UTC, PixNyb commented on src/project/listeners/key_listener.cpp
> +
Gooi ff een logic error bij unimplemented functions en zet er een // TODO: neer, dat pakken de IDE's op en dan weten we dat het nog niet af is

2023-11-18 14:05 UTC, PixNyb commented on src/project/listeners/mouse_listener.cpp
> +            if (enumOfType == ActionType::JUMP) {
Zelfde verhaal als [key_listener.cpp](/src/project/listeners/key_listener.cpp), switch aub

2023-11-18 14:05 UTC, PixNyb commented on src/project/managers/input_manager.cpp
SDL referenties (?)

2023-11-19 19:02 UTC, DaanGroot536 commented on include/project/core/events/action_type.hpp
> +    static ActionType convertStringToEnum(std::string enumName);
Function names moeten CamelCase

2023-11-19 19:17 UTC, DaanGroot536 commented on include/project/managers/input_manager.hpp
> +    void update(std::vector<SDL_Event>& events);
Overal graag ff netjes CamelCase gebruiken

2023-11-19 19:20 UTC, DaanGroot536 commented on src/facades/sdl2/sdl2_input_handler.cpp
> +#include "sdl2_input_handler.hpp"
volgens mij gebruikten wij geen namen van libraries in classnames

2023-11-19 19:34 UTC, DaanGroot536 commented on src/project/core/events/action_type.cpp
> +const ActionType ActionType::JUMP("JUMP");
Moet je zo niet voor elk enum item een nieuwe methode schrijven? Beetje onhandig

2023-11-19 19:39 UTC, DaanGroot536 requested changes
Ik zie heel sporadisch gebruik van CamelCase. Er komt veel [[no-discard]] voor, geen idee of dat van veel nut is bij elke functie. Roël heeft vgm de rest wel gezien

2023-11-21 08:37 UTC, PixNyb commented on include/facades/sdl2/sdl_event_listener.hpp
> +    void PollEvents();
Comments

2023-11-21 08:37 UTC, PixNyb commented on include/facades/i_input_facade.hpp
> +    virtual ~IInputFacade() = default;
Comments

2023-11-21 08:37 UTC, PixNyb commented on include/facades/input_facade.hpp
> +    std::unique_ptr<SDLEventListener> eventListener;
Comments

2023-11-21 08:37 UTC, PixNyb commented on include/project/core/events/key_event.hpp
> +class KeyEvent : public Event
Comments/docs

2023-11-21 08:37 UTC, PixNyb commented on include/project/core/events/mouse_event.hpp
> +{
Docs

2023-11-21 08:37 UTC, PixNyb commented on include/project/listeners/key_listener.hpp
> +class KeyListener : public IKeyListener {
Docs

2023-11-21 08:37 UTC, PixNyb commented on include/project/listeners/mouse_listener.hpp
> +  public:
Docs

2023-11-21 08:37 UTC, PixNyb commented on sandbox/main.cpp
> +#include "i_input_facade.hpp"
Docs

2023-11-21 08:38 UTC, PixNyb commented on src/facades/sdl_input_facade.cpp
> +    for (const auto &keyEvent : eventListener->GetPolledKeyEvents())
Kijk nog even of je dit op kan schonen

2023-11-21 08:38 UTC, PixNyb commented on src/project/core/events/key_event.cpp
> +KeyEvent::KeyEvent(KeyCode keyCode, bool isKeyDown) : Event(keyCode)
Probeer dit nog even te simplifyen

2023-11-21 08:39 UTC, PixNyb commented on src/project/core/events/mouse_event.cpp
> +MouseEvent::MouseEvent(KeyCode keyCode) : Event(keyCode)
Implementatie?

2023-11-21 08:39 UTC, PixNyb commented on src/project/listeners/key_listener.cpp
> +void KeyListener::OnKeyPressed() {
Logica per key configurable maken met de bind functie?

2023-11-21 08:40 UTC, PixNyb commented on src/project/listeners/mouse_listener.cpp
> +void MouseListener::OnMouseMoved() {
Idem dito, zie [key_listener.cpp](/src/project/listeners/key_listener.cpp)

2023-11-22 08:46 UTC, closed without merging