Feature/audio
PixNyb/Avans-SPCPRJ13-ENGINE pull request #48
Opened 2023-11-23 13:44 UTC by ChocoMelvin

## Beschrijving

Audio als game component zodat de gebruiker geluid kan horen en kan koppelen aan een game object.

Hierbij is geen gebruikgemaakt van de audio manager zoals eerst afgesproken in het design.
SFML maakt allemaal losstaande componenten en het maakt geen gebruik van een mixer, waardoor het enige nut nog het beheren van instances zou zijn, die hij zelf toch niet volledig kan controleren.

Verder is de wrapper een beetje dubbelop, hiervoor is wel bewust gekozen, omdat hier wat meer functionaliteit in zit die we evt zouden kunnen gebruiken en we ons zo makkelijker aan de API kunnen houden.

## Gerelateerde issues/taken

[USERSTORY 12 : Muziek en geluid](https://app.clickup.com/t/8692mmp48)

## Definition of Done

- [ ] Het gebruik van extern toegankelijke functionaliteiten voor de gameontwikkelaar is gedocumenteerd in de [USAGE.md](/USAGE.md).
- [ ] De code voldoet indien van toepassing aan de acceptatiecriteria van de issue/taak.
- [ ] De code voldoet aan de code style van het project zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code bevat documentatie zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] Er zijn unit tests geschreven voor de code indien van toepassing.
- [ ] De code is getest en slaagt voor alle bestaande en nieuwe unit tests.

2023-11-24 20:02 UTC, Martijn-V1 reviewed
Ziet er allemaal goed uit, pitch werkt en is het volume ook apart regelbaar?

Misschien kan er een unit test worden gemaakt met behulp van een test muziek bestand vanuit een folder

2023-11-25 12:39 UTC, PixNyb commented on include/api/audio_source.hpp
> +#include "audio_facade.hpp"
Unused import

2023-11-25 12:45 UTC, PixNyb commented on include/facades/audio_facade.hpp
> +#include "sfml_sound.hpp"
Unused import

2023-11-25 12:46 UTC, PixNyb commented on include/facades/audio_facade.hpp
File heeft geen class of functiedocumentatie

2023-11-25 12:47 UTC, PixNyb commented on include/facades/i_audio_facade.hpp
File heeft geen class/member documentatie

2023-11-25 12:47 UTC, PixNyb commented on include/facades/i_sound.hpp
Klassedocumentatie

2023-11-25 12:47 UTC, PixNyb commented on sandbox/main.cpp
Revert dit

2023-11-25 12:50 UTC, PixNyb commented on src/project/core/engine.cpp
> +
Waarom is dit een change lol

2023-11-25 12:51 UTC, PixNyb commented on src/project/core/engine.cpp
De `#include <thread>` in deze file is unused. Is hier wat aangepast?

2023-11-25 12:52 UTC, PixNyb commented on CMakeLists.txt
CMakeLists.txt hebben geen spatie tussen keyword en ()

2023-11-25 12:56 UTC, PixNyb reviewed
Zoals @Martijn-V1 kijk even of je dit kan unit testen. Download file via curl of maak een `tests/assets/` folder ofzo. Verder ziet t er netjes uit.

2023-11-25 13:03 UTC, ChocoMelvin commented on include/api/audio_source.hpp
Die staat ook al in de audio instance, dan moet ik beide vars bij gaan houden, kan ik doen, maar is miss niet handig?

2023-11-25 13:04 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +
Wss tijdens het verwijderen van de audio manager, kan de newline weghalen.

2023-11-25 13:10 UTC, PixNyb commented on include/api/audio_source.hpp
Ah okeoke np

2023-11-27 15:46 UTC, ChocoMelvin commented on include/facades/i_audio_facade.hpp
Eigenlijk is deze hele klasse niet meer nodig.

2023-11-27 15:51 UTC, ChocoMelvin commented on CMakeLists.txt
Daar is CLION het mee oneens, maar ik zie idd dat het nergens anders zo is. Heb het bijgesteld.

2023-11-30 14:24 UTC, PixNyb requested changes

2023-11-30 14:24 UTC, PixNyb commented on include/api/audio_source.hpp
> +#include "audio_facade.hpp"
Deze is nogsteeds van toepassing

2023-11-30 14:24 UTC, PixNyb commented on include/facades/audio_facade.hpp
> +#include "sfml_sound.hpp"
Nogsteeds een unused import

2023-12-01 11:55 UTC, PixNyb requested changes

2023-12-01 11:55 UTC, PixNyb commented on include/api/audio_source.hpp
> +    std::shared_ptr<ISound> sound;
Param docs?

2023-12-01 11:55 UTC, PixNyb commented on include/api/audio_source.hpp
>    private:
Param docs zien er wat anders uit, is net geupdate in de [development guidelines](/DEVELOPMENT_GUIDELINES.md)

2023-12-01 18:47 UTC, ChocoMelvin commented on include/api/audio_source.hpp
> +    std::shared_ptr<ISound> sound;
Param wat? Dit is een private shared_ptr

2023-12-01 18:48 UTC, ChocoMelvin commented on include/api/audio_source.hpp
> +    std::shared_ptr<ISound> sound;
Denk dat je heir gewoon de var docs bedoelde, die zal ik ff toepassen iig.

2023-12-02 13:43 UTC, PixNyb requested changes
Klein docs puntje en een unused import, verder nette PR. Als dat gefixt is mag t wat mij betreft door

2023-12-02 13:43 UTC, PixNyb commented on include/api/audio_source.hpp
> +#include <iostream>
Unused import?

2023-12-02 13:43 UTC, PixNyb commented on include/api/audio_source.hpp
> +    std::shared_ptr<ISound> sound;
Ja sorry lol, property docs idd. DEVELOPMENT_GUIDELINES.md#89

2023-12-02 14:32 UTC, ChocoMelvin commented
Gedelete comment was een duplicate van de in-code comment.

2023-12-02 14:42 UTC, PixNyb approved these changes

2023-12-02 14:42 UTC, merged