Feature/contact listening
PixNyb/Avans-SPCPRJ13-ENGINE pull request #49
Opened 2023-11-23 14:42 UTC by DaanGroot536

PR voor de contactlisteners + koppeling naar behaviourscripts

De changes omvatten voornamelijk het toevoegen van de contactlisteners, de weak reference naar de physicsmanager in het gameobject en het aanroepen van de behaviourscripts.

Er zat nog een issue in het updaten van de posities van de transforms. Die is nu gefixt met deze PR.

De Physics userstory/taak opzich is nu in de basis klaar. Er kunnen nog dingen toegevoegd worden als friction en bouncing. Dit moet na deze PR even besproken worden.

How to use is geschreven
Code voldoet aan acceptatiecriteria
Testen is helaas niet echt te doen hier
Tests falen ofc niet
Doxygen is bijgevoegd in hpp's
Reviews wordt geregeld

2023-11-26 11:59 UTC, Maxuuuu commented on include/facades/box2d/contact_listener.hpp
> +#include "box2d/b2_contact.h"
Third party lib includes moesten als het goed is ook met '<>' zijn.

2023-11-26 12:27 UTC, Maxuuuu requested changes
Buiten een paar kleine import code guideline dingetjes om ziet het er netjes uit. De physics demo werkt op het moment niet, door de afwezigheid van de BehaviourScriptTest. Deze code heb ik wel kunnen testen in de game, hier lijkt het goed te werken. Als je die kleine changes doorvoert is het voor mij approved.

2023-11-26 12:27 UTC, Maxuuuu commented on include/project/managers/physics_manager.hpp
>  #include "memory"
Zijn includes van een vorige PR, maar moeten ook '<>' gebruiken.

2023-11-26 12:30 UTC, ChocoMelvin commented on src/facades/box2d/contact_listener.cpp
> +    std::cout << tag1 << " is touching " << tag2 << std::endl;
Wil je dit altijd loggen of moet dit in een soort debug class gebeuren?

2023-11-26 12:32 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +    Time::TimeScale(2);
Dit is niet de bedoeling, timescale is altijd 1, tenzij de gebruiker dit anders wil. De params voor physics moet je ergens anders tweaken.

2023-11-26 12:34 UTC, ChocoMelvin commented on src/facades/box2d/contact_listener.cpp
> +    std::cout << tag1 << " stopped touching " << tag2 << std::endl;
Zelfde als bij vorige, we hebben wss iets van een debug class nodig zoals in het diagram staat, misschien ff todo bij en een clickup taak

2023-11-26 12:58 UTC, ChocoMelvin approved these changes

2023-11-26 12:58 UTC, ChocoMelvin commented on src/facades/box2d/contact_listener.cpp
> +void ContactListener::BeginContact(b2Contact *contact)
Bij beide functies ga je door te veel objecten heen en je voert hier twee keer dezelfde code uit voor twee verschillende objecten. Dat is een goede indicatie dat er control-flow wise iets misgaat.

2023-11-26 12:58 UTC, ChocoMelvin commented on src/facades/box2d/contact_listener.cpp
> +void ContactListener::BeginContact(b2Contact *contact)
```cpp
auto findGameObject = [&](b2Body *body) {
    auto it = std::find_if(gameObjects.begin(), gameObjects.end(), [body](const auto &pair) { return pair.second == body; });
    return (it != gameObjects.end()) ? it->first : nullptr;
};

auto gameObjectA = findGameObject(bodyA);
auto gameObjectB = findGameObject(bodyB);
```

Zoiets zou je ook kunnen gebruiken misschien?

Kleine uitleg: `[&](b2Body *body)` betekent dat dat wat je gebruikt by reference wordt doorgegeven, [=] zou by value betekenen in lambdas.

2023-11-26 12:58 UTC, ChocoMelvin commented on src/facades/box2d/contact_listener.cpp
> +void ContactListener::EndContact(b2Contact *contact)
Zelfde als bovenstaande

2023-11-26 13:01 UTC, ChocoMelvin commented
Misschien moeten we een config object en een init() gaan aanmaken in de Engine, want er moeten nu eigenlijk te veel verschillende stappen worden uitgevoerd. Maar dat hoeft niet per se in deze PR, moeten ff een taakje voor aanmaken.

2023-11-27 09:49 UTC, PixNyb requested changes

2023-11-27 09:49 UTC, PixNyb commented on include/facades/box2d/contact_listener.hpp
> +#include <vector>
Unused import

2023-11-27 16:05 UTC, DaanGroot536 commented on src/facades/box2d/contact_listener.cpp
> +    std::cout << tag1 << " is touching " << tag2 << std::endl;
ik haal ze weg, was om de contact listening te debuggen

2023-11-27 16:06 UTC, DaanGroot536 commented on src/project/core/engine.cpp
> +    Time::TimeScale(2);
ah was deze vergeten weg te halen, excuus

2023-11-27 16:07 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +    Time::TimeScale(2);
Ah okay makes sense :)

2023-11-27 16:08 UTC, DaanGroot536 commented on src/facades/box2d/contact_listener.cpp
> +    std::cout << tag1 << " stopped touching " << tag2 << std::endl;
clickup taak is aangemaakt, ik ga er mee aan de slag

2023-11-27 17:42 UTC, PixNyb requested changes

2023-11-27 17:42 UTC, PixNyb commented on include/facades/box2d/contact_listener.hpp
> +class ContactListener : public b2ContactListener
Class documentatie

2023-11-27 17:42 UTC, PixNyb commented on include/facades/physics_facade.hpp
> + * The PhysicsFacade is responsible for all physics related logic. It gives the engine the tools to
Zet dit even in de class documentatie

2023-11-27 17:42 UTC, PixNyb commented on include/project/managers/physics_manager.hpp
>  class PhysicsManager
Class documentatie

2023-11-27 17:42 UTC, PixNyb commented on src/facades/box2d/contact_listener.cpp
> +#include <iostream>
Unused import

2023-11-27 21:43 UTC, PixNyb approved these changes
lgtm 🙈

2023-11-28 10:44 UTC, Maxuuuu approved these changes
Ziet er goed uit.

2023-11-28 10:46 UTC, merged