Added game object children
PixNyb/Avans-SPCPRJ13-ENGINE pull request #51
Opened 2023-11-25 13:12 UTC by ChocoMelvin

- Adjusted managers to be able to use the children
- Removed GameObjectList
- SetParent now adjusts the children
- Set max bounds to prevent infinite recursion

## Beschrijving

## Gerelateerde issues/taken

## Definition of Done

- [ ] Het gebruik van extern toegankelijke functionaliteiten voor de gameontwikkelaar is gedocumenteerd in de [USAGE.md](/USAGE.md).
- [ ] De code voldoet indien van toepassing aan de acceptatiecriteria van de issue/taak.
- [ ] De code voldoet aan de code style van het project zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code bevat documentatie zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] Er zijn unit tests geschreven voor de code indien van toepassing.
- [ ] De code is getest en slaagt voor alle bestaande en nieuwe unit tests.

2023-11-25 14:22 UTC, PixNyb requested changes

2023-11-25 14:22 UTC, PixNyb commented on include/project/managers/behaviour_script_manager.hpp
> +
Class documentation

2023-11-25 14:22 UTC, PixNyb commented on include/utility/game_object_utility.hpp
> +
Class documentation

2023-11-25 14:22 UTC, PixNyb commented on tests/game_object_test.cpp
> +#include "core_constants.hpp"
Unused import

2023-11-25 14:22 UTC, PixNyb commented on vcpkg.json
> +  "builtin-baseline": "3265c187c74914aa5569b75355badebfdbab7987",
Waarom is dit veranderd?

2023-11-25 14:22 UTC, PixNyb commented on src/api/game_object.cpp
> +        auto it = std::find(parent->children.begin(), parent->children.end(), shared_from_this());
```
streambuf_iterator.h(434, 5): Candidate template ignored: could not match 'istreambuf_iterator' against '__normal_iterator'
```

2023-11-25 14:23 UTC, ChocoMelvin commented on include/project/managers/behaviour_script_manager.hpp
> +
Hoort niet echt meer bij deze PR he.

2023-11-25 14:24 UTC, ChocoMelvin commented on src/api/game_object.cpp
> +        auto it = std::find(parent->children.begin(), parent->children.end(), shared_from_this());
Dat is niet zo bij mij, elaborate

2023-11-25 14:26 UTC, ChocoMelvin commented on vcpkg.json
> +  "builtin-baseline": "3265c187c74914aa5569b75355badebfdbab7987",
Omdat het niet meer draaide bij mij door mismatch

2023-11-25 14:51 UTC, ChocoMelvin commented on src/api/game_object.cpp
> +        auto it = std::find(parent->children.begin(), parent->children.end(), shared_from_this());
Het build ook gewoon, dus dat zul je bij jezelf op moeten lossen.

2023-11-26 11:38 UTC, DaanGroot536 reviewed
2 dingetjes gecomment. Lijkt verder helemaal guten.

2023-11-26 11:38 UTC, DaanGroot536 commented on include/project/core/core_constants.hpp
> +const int MAX_NESTED_CHILDREN = 10; ///< The maximum amount of nested children a game object can
denk dat 5 wel meer dan genoeg is?

2023-11-26 11:38 UTC, DaanGroot536 commented on sandbox/main.cpp
>   *
deze ff in de demo map zetten?

2023-11-27 09:26 UTC, PixNyb commented on sandbox/main.cpp
>   *
Welke demo map

2023-11-27 15:58 UTC, ChocoMelvin commented on sandbox/main.cpp
>   *
Wat roël zegt en eigenlijk is het niet heel demo-waardig, het is vooral voor jullie om te testen dat mijn zooi werkt.

2023-11-27 16:12 UTC, DaanGroot536 approved these changes

2023-11-27 16:12 UTC, merged