US 09: Animerende objecten middels spritesheet
PixNyb/Avans-SPCPRJ13-ENGINE pull request #53
Opened 2023-11-28 19:21 UTC by RobinPijnappelsAvans

## Beschrijving

Ik heb ervoor gezorgd dat het mogelijk is om sprites te renderen op het scherm en daarnaast ook spritesheets doormiddel van de Animator en bijbehorende AnimationStates

## Gerelateerde issues/taken

[USERSTORY 09 : Animerende objecten middels spritesheets](https://app.clickup.com/t/8692mmny0)
[Render sprite and ui object](https://app.clickup.com/t/869358bwh)

## Definition of Done

- [ ] Het gebruik van extern toegankelijke functionaliteiten voor de gameontwikkelaar is gedocumenteerd in de [USAGE.md](/USAGE.md).
- [ ] De code voldoet indien van toepassing aan de acceptatiecriteria van de issue/taak.
- [ ] De code voldoet aan de code style van het project zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code bevat documentatie zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code is getest en slaagt voor alle bestaande en nieuwe unit tests.

2023-11-28 19:24 UTC, ChocoMelvin commented on src/api/transform.cpp
> +Transform Transform::CombineWith(const Transform &other) const {
Als je alleen optelt kun je ook de + operator overloaden

2023-11-28 19:25 UTC, ChocoMelvin commented on include/api/animation_state.hpp
> +    AnimationState(int totalFrames, float frameTime);
Private constructor niet duidelijk waarvoor het is (docs)

2023-11-28 19:29 UTC, ChocoMelvin commented on sandbox/main.cpp
niet vergeten te reverten vóór merge

2023-11-28 19:33 UTC, ChocoMelvin commented on src/api/sprite.cpp
> +        : color(1.0, 1.0, 1.0, 1.0),  // Initializing color to white (or any other default)
Misschien een soort van defaults in constants maken, maar volgens mij maakt het niet heelll veel uit?

2023-11-28 19:35 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +        auto events = graphicsFacade->PollEvents();
lege for loop waar niets mee gedaan wordt, denk dat dit nu eigenlijk vervangen is/kan worden met de poll uit de ioFacade? Is niet per se jouw PR ofc.

2023-11-28 19:35 UTC, ChocoMelvin commented on src/project/core/engine.cpp
> +        auto events = graphicsFacade->PollEvents();
evt taakje voor aanmaken

2023-11-28 19:36 UTC, ChocoMelvin reviewed
Functioneel check ik het morgen ff wat beter.
Enige wat verder kleine feedback is, is dat de control flow op sommige plekke misschien verbeterd kan worden.
Dus eerder een return in een groot if blokje.

2023-11-28 19:38 UTC, ChocoMelvin commented on include/api/animator.hpp
> +    void Update(float deltaTime);
virtual void OnUpdate(); kun je overriden van een behaviour script, delta time haal je dan uit de static Time:: klasse

2023-11-28 19:39 UTC, ChocoMelvin commented on include/api/animation_state.hpp
> +    void Update(float deltaTime);
Docs: Waarom twee verschillende updates?

2023-11-28 19:40 UTC, ChocoMelvin commented on src/api/animator.cpp
> +    {
Dubbele nested scope blocks

2023-11-28 19:42 UTC, ChocoMelvin commented on src/project/managers/render_manager.cpp
We moeten ff onze formatters gelijkstellen denk ik

2023-11-28 19:44 UTC, ChocoMelvin commented on include/api/transform.hpp
> +    Transform CombineWith(const Transform &other) const;
Wat is het verschil met de + overload die ik hiervoor al heb gemaakt?

2023-12-01 11:25 UTC, PixNyb commented on include/api/animation_state.hpp
>      std::map<std::string, AnimationState> states;
Property documentatie gaat zo:
```cpp
std::map<std::string, AnimationState> states; ///< Map to hold various animation states.
```

2023-12-01 11:33 UTC, PixNyb requested changes

2023-12-01 11:33 UTC, PixNyb commented on include/api/animation_state.hpp
> +    AnimationState(int startFrameIndex, int endFrameIndex, float frameDuration)
Functie documentatie omdat dit een overload is met verschillende props

2023-12-01 11:33 UTC, PixNyb commented on include/api/animator.hpp
> +    [[gnu::used]] void AddState(const std::string &name, const AnimationState &state);
Wat is dit?
```
[[gnu::used]]
```

2023-12-01 11:33 UTC, PixNyb commented on include/api/animator.hpp
> +    std::unique_ptr<AnimationState> currentState;
Zie [animation_state.hpp](/include/api/animation_state.hpp)

2023-12-01 11:33 UTC, PixNyb commented on include/api/animator.hpp
> +    std::map<std::string, AnimationState> states;
Idem dito

2023-12-01 11:33 UTC, PixNyb commented on include/facades/graphics_facade.hpp
> +        textureCache; /**< Map of texture file paths to SDL_Texture pointers. */
`///<` ipv `/**< ... */`

2023-12-01 11:33 UTC, PixNyb commented on include/facades/graphics_facade.hpp
>  #include "sdl_render.hpp"
Unused import

2023-12-01 11:33 UTC, PixNyb commented on include/project/core/events/event.hpp
> +
why

2023-12-01 11:33 UTC, PixNyb commented on src/api/animation_state.cpp
Included header [game_object.hpp](/src/api/game_object.cpp) is not used directly.

2023-12-01 12:14 UTC, DaanGroot536 submitted a review, later dismissed

2023-12-05 11:57 UTC, DaanGroot536 approved these changes

2023-12-05 12:30 UTC, PixNyb approved these changes
Goedzo maatje

2023-12-05 12:39 UTC, merged