Feature/button
PixNyb/Avans-SPCPRJ13-ENGINE pull request #62
Opened 2023-12-06 21:02 UTC by Martijn-V1

## Beschrijving

Clicklisteners aangemaakt voor de buttons
Button factory aangemaakt

## Gerelateerde issues/taken

https://app.clickup.com/t/8692mmntr

## Definition of Done

- [ ] Het gebruik van extern toegankelijke functionaliteiten voor de gameontwikkelaar is gedocumenteerd in de [USAGE.md](/USAGE.md).
- [ ] De code voldoet indien van toepassing aan de acceptatiecriteria van de issue/taak.
- [ ] De code voldoet aan de code style van het project zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code bevat documentatie zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] Er zijn unit tests geschreven voor de code indien van toepassing.
- [ ] De code is getest en slaagt voor alle bestaande en nieuwe unit tests.

2023-12-08 14:13 UTC, ChocoMelvin commented on src/facades/sdl2/facades/sdl_input_facade.cpp
> +            buttonClickListener.SetMousePosition(this->GetMousePosition());
Dit zou de listener eigenlijk zelf op moeten halen van de facade.
Als dat lastig is, laat het maar staan, maar dit is wel een paar keer vermeld.

2023-12-08 14:17 UTC, ChocoMelvin commented on src/api/button.cpp
>  Button::Button() : interactable(true), onClick(nullptr)
Nu heeft button alsnog nooit een referentie naar de listener, hoe gaan we de listener ooit op kunnen schonen?

2023-12-11 12:36 UTC, Maxuuuu requested changes
Heb een paar kleine opmerkingen. Verder heb ik het ook nog niet functioneel kunnen testen doordat het niet lijkt te werken met feature/hud van de game.

2023-12-11 12:36 UTC, Maxuuuu commented on include/project/utility/factories/button_factory.hpp
> +     * @param inputFacade Shared pointer to the input facade for handling user input.
Docs matcht de functie niet, specifiek de parameters.

2023-12-11 12:36 UTC, Maxuuuu commented on src/project/utility/factories/button_factory.cpp
> +    button->OnClick([]() { std::cout << "Button Clicked!" << std::endl; });
Moet dit er nog in staan op development?

2023-12-12 12:48 UTC, Maxuuuu approved these changes
Heb het nu getest en het werkt goed. Lekker bezig.

2023-12-13 09:08 UTC, merged