Feature/game items
PixNyb/Avans-SPCPRJ13-ENGINE pull request #75
Opened 2023-12-16 15:03 UTC by DaanGroot536

## Beschrijving

Deze PR update een aantal dingen in de collider om behaviourscripts bruikbaar te maken.
Contact listener update nu de lijst met bodies. (bullets zijn nu werkend hierdoor)

## Gerelateerde issues/taken

## Definition of Done

- [ ] Het gebruik van extern toegankelijke functionaliteiten voor de gameontwikkelaar is gedocumenteerd in de [USAGE.md](/USAGE.md).
- [ ] De code voldoet indien van toepassing aan de acceptatiecriteria van de issue/taak.
- [ ] De code voldoet aan de code style van het project zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] De code bevat documentatie zoals beschreven in de [DEVELOPMENT_GUIDELINES.md](/DEVELOPMENT_GUIDELINES.md).
- [ ] Er zijn unit tests geschreven voor de code indien van toepassing.
- [ ] De code is getest en slaagt voor alle bestaande en nieuwe unit tests.

2023-12-16 22:29 UTC, PixNyb requested changes
Prima maar ff wat docs dingetjes

2023-12-16 22:29 UTC, PixNyb commented on include/facades/box2d/contact_listener.hpp
> +    void UpdateBodies(std::map<std::shared_ptr<GameObject>, b2Body *> gameObjects);
Docs <3

2023-12-16 22:29 UTC, PixNyb commented on include/facades/physics_facade.hpp
> +#include "contact_listener.hpp"
Unused dependencies, collider.hpp en debug_renderer.hpp

2023-12-16 22:29 UTC, PixNyb commented on include/facades/physics_facade.hpp
> +    ContactListener* contactListener;
Docs

2023-12-16 22:29 UTC, PixNyb commented on include/project/managers/level_manager.hpp
> +    int GetCurrentLevelID() { return currentLevelID; }
Doxygen docs

2023-12-17 10:39 UTC, DaanGroot536 commented on include/facades/physics_facade.hpp
> +#include "contact_listener.hpp"
niet unused

2023-12-17 10:55 UTC, PixNyb approved these changes

2023-12-17 11:05 UTC, merged